import Link from 'next/link'
import {Check,Search,X} from 'lucide-react'
import {AdminPageHeading,SubmitButton} from '@/components/admin-ui'
import {EmptyState,StatusPill} from '@/components/ui'
import {formatPKR} from '@/lib/data'
import {requireAdmin} from '@/lib/site'
import {updatePayment} from '../actions'
export const metadata={title:'Payments | Fitness Pro Admin'}
function memberInfo(value:unknown){const item=Array.isArray(value)?value[0]:value;return item&&typeof item==='object'?item as {id:string;full_name:string;phone:string}:null}
export default async function Payments({searchParams}:{searchParams:Promise<{status?:string;q?:string}>}){const [{supabase},query]=await Promise.all([requireAdmin(),searchParams]);const status=['all','pending','verified','rejected','cancelled'].includes(query.status||'')?query.status!:'pending';let request=supabase.from('payment_requests').select('*,members(id,full_name,phone)').order('submitted_at',{ascending:false});if(status!=='all')request=request.eq('status',status);const {data:payments}=await request;const q=(query.q||'').toLowerCase();const shown=(payments||[]).filter(p=>{const m=memberInfo(p.members);return !q||m?.full_name.toLowerCase().includes(q)||m?.phone.includes(q)||String(p.reference||'').toLowerCase().includes(q)});return <><AdminPageHeading eyebrow="Manual verification" title="Payments" copy="Review member payment requests. Verify only after confirming the funds through an official Fitness Pro account."/><form className="adminFilterBar"><label className="searchBox"><Search/><input name="q" defaultValue={query.q||''} placeholder="Member, phone or reference"/></label><select name="status" defaultValue={status}><option value="all">All statuses</option><option value="pending">Pending</option><option value="verified">Verified</option><option value="rejected">Rejected</option><option value="cancelled">Cancelled</option></select><button className="button buttonSmall">Filter</button></form>{shown.length?<div className="paymentAdminGrid">{shown.map(p=>{const member=memberInfo(p.members);return <article className="adminCard" key={p.id}><div className="rowBetween"><StatusPill value={p.status}/><time>{new Date(p.submitted_at).toLocaleString('en-PK')}</time></div><h2>{p.selection_name}</h2><strong className="requestAmount">{formatPKR(p.amount)}</strong><dl><div><dt>Member</dt><dd>{member?<Link href={`/admin/members/${member.id}`}>{member.full_name}</Link>:'Removed member'}</dd></div><div><dt>Method</dt><dd>{String(p.method).replace(/^./,x=>x.toUpperCase())}</dd></div><div><dt>Reference</dt><dd>{p.reference||'Not required'}</dd></div><div><dt>Note</dt><dd>{p.note||'—'}</dd></div></dl>{p.status==='pending'&&<div className="buttonRow"><form action={updatePayment}><input type="hidden" name="id" value={p.id}/><input type="hidden" name="status" value="verified"/><SubmitButton confirm="Confirm that this payment has been independently verified?"><Check/>Verify</SubmitButton></form><form action={updatePayment}><input type="hidden" name="id" value={p.id}/><input type="hidden" name="status" value="rejected"/><SubmitButton className="button buttonSmall buttonGhost"><X/>Reject</SubmitButton></form></div>}</article>})}</div>:<EmptyState title="No payment requests match" copy="New member submissions will appear here."/>}</>}
