'use server'
import {revalidatePath} from 'next/cache'
import {redirect} from 'next/navigation'
import {requireAdmin} from '@/lib/site'

const text=(fd:FormData,key:string)=>String(fd.get(key)||'').trim()
const optional=(fd:FormData,key:string)=>text(fd,key)||null
const numberOrNull=(fd:FormData,key:string)=>{const raw=text(fd,key);return raw===''?null:Number(raw)}
const checked=(fd:FormData,key:string)=>fd.get(key)==='on'||fd.get(key)==='true'
const slugify=(input:string)=>input.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')

async function uploadImage(fd:FormData,key:string,folder:string){const file=fd.get(key);if(!(file instanceof File)||file.size===0)return null;if(file.size>4*1024*1024)throw new Error('Image must be 4 MB or smaller.');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Use a JPG, PNG or WebP image.');const {supabase}=await requireAdmin();const extension=file.name.split('.').pop()?.toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg';const path=`${folder}/${crypto.randomUUID()}.${extension}`;const {error}=await supabase.storage.from('fitness-pro-media').upload(path,file,{contentType:file.type,upsert:false});if(error)throw new Error(error.message);return supabase.storage.from('fitness-pro-media').getPublicUrl(path).data.publicUrl}

export async function updateMessage(fd:FormData){const {supabase}=await requireAdmin();const id=text(fd,'id');const {error}=await supabase.from('contact_messages').update({status:text(fd,'status'),admin_note:optional(fd,'admin_note')}).eq('id',id);if(error)throw new Error(error.message);revalidatePath('/admin/messages')}
export async function deleteMessage(fd:FormData){const {supabase}=await requireAdmin();const {error}=await supabase.from('contact_messages').delete().eq('id',text(fd,'id'));if(error)throw new Error(error.message);revalidatePath('/admin/messages')}

export async function saveMember(fd:FormData){const {supabase,user}=await requireAdmin();const id=text(fd,'id');const approval=text(fd,'approval_status')||'pending';const record={full_name:text(fd,'full_name'),phone:text(fd,'phone'),email:optional(fd,'email'),plan_id:optional(fd,'plan_id'),join_date:optional(fd,'join_date'),expiry_date:optional(fd,'expiry_date'),custom_duration_months:numberOrNull(fd,'custom_duration_months'),admission_fee_paid:checked(fd,'admission_fee_paid'),notes:optional(fd,'notes'),membership_status:text(fd,'membership_status')||'active',approval_status:approval,approved_at:approval==='approved'?new Date().toISOString():null,approved_by:approval==='approved'?user.id:null};if(id){const {error}=await supabase.from('members').update(record).eq('id',id);if(error)throw new Error(error.message);revalidatePath(`/admin/members/${id}`);redirect(`/admin/members/${id}?saved=1`)}else{const {data,error}=await supabase.from('members').insert(record).select('id').single();if(error)throw new Error(error.message);redirect(`/admin/members/${data.id}?created=1`)}}
export async function setMemberState(fd:FormData){const {supabase,user}=await requireAdmin();const id=text(fd,'id'),approval=optional(fd,'approval_status'),membership=optional(fd,'membership_status');const patch:Record<string,unknown>={};if(approval){patch.approval_status=approval;patch.approved_at=approval==='approved'?new Date().toISOString():null;patch.approved_by=approval==='approved'?user.id:null}if(membership)patch.membership_status=membership;const {error}=await supabase.from('members').update(patch).eq('id',id);if(error)throw new Error(error.message);revalidatePath('/admin/members');revalidatePath('/admin/registrations')}
export async function deleteMember(fd:FormData){const {supabase}=await requireAdmin();const {error}=await supabase.from('members').delete().eq('id',text(fd,'id'));if(error)throw new Error(error.message);redirect('/admin/members?deleted=1')}

export async function savePlan(fd:FormData){const {supabase}=await requireAdmin();const id=text(fd,'id'),name=text(fd,'name');const record={name,slug:text(fd,'slug')||slugify(name),price:numberOrNull(fd,'price'),billing_period:text(fd,'billing_period')||'Monthly',tagline:optional(fd,'tagline'),features:text(fd,'features').split('\n').map(x=>x.trim()).filter(Boolean),is_popular:checked(fd,'is_popular'),is_active:checked(fd,'is_active'),sort_order:Number(text(fd,'sort_order')||0)};if(id){const {error}=await supabase.from('membership_plans').update(record).eq('id',id);if(error)throw new Error(error.message);redirect('/admin/plans?saved=1')}const {error}=await supabase.from('membership_plans').insert(record);if(error)throw new Error(error.message);redirect('/admin/plans?created=1')}
export async function deletePlan(fd:FormData){const {supabase}=await requireAdmin();const {error}=await supabase.from('membership_plans').delete().eq('id',text(fd,'id'));if(error)throw new Error(error.message);revalidatePath('/admin/plans')}

export async function saveDietPlan(fd:FormData){const {supabase}=await requireAdmin();const id=text(fd,'id'),name=text(fd,'name');const record={name,slug:text(fd,'slug')||slugify(name),price:numberOrNull(fd,'price'),was_price:numberOrNull(fd,'was_price'),blurb:optional(fd,'blurb'),is_active:checked(fd,'is_active'),sort_order:Number(text(fd,'sort_order')||0)};if(id){const {error}=await supabase.from('diet_plans').update(record).eq('id',id);if(error)throw new Error(error.message)}else{const {error}=await supabase.from('diet_plans').insert(record);if(error)throw new Error(error.message)}redirect('/admin/pricing?saved=1')}
export async function deleteDietPlan(fd:FormData){const {supabase}=await requireAdmin();const {error}=await supabase.from('diet_plans').delete().eq('id',text(fd,'id'));if(error)throw new Error(error.message);revalidatePath('/admin/pricing')}
export async function saveRates(fd:FormData){const {supabase}=await requireAdmin();const keys=['daily_without_training','daily_with_training','weekly_without_training','weekly_with_training'];for(const key of keys){const {error}=await supabase.from('pricing_rates').upsert({key,label:text(fd,`${key}_label`),amount:Number(text(fd,key)||0),sort_order:Number(text(fd,`${key}_order`)||0)});if(error)throw new Error(error.message)}revalidatePath('/admin/pricing');redirect('/admin/pricing?rates=saved')}
export async function saveDuration(fd:FormData){const {supabase}=await requireAdmin();const id=text(fd,'id');const record={label:text(fd,'label'),months:Number(text(fd,'months')),bronze_price:Number(text(fd,'bronze_price')),silver_price:Number(text(fd,'silver_price')),gold_price:Number(text(fd,'gold_price')),sort_order:Number(text(fd,'sort_order')||0),is_active:checked(fd,'is_active')};const result=id?await supabase.from('duration_prices').update(record).eq('id',id):await supabase.from('duration_prices').insert(record);if(result.error)throw new Error(result.error.message);redirect('/admin/pricing?duration=saved')}
export async function deleteDuration(fd:FormData){const {supabase}=await requireAdmin();const {error}=await supabase.from('duration_prices').delete().eq('id',text(fd,'id'));if(error)throw new Error(error.message);revalidatePath('/admin/pricing')}

export async function markAttendance(fd:FormData){const {supabase,user}=await requireAdmin();const status=text(fd,'status');const record={member_id:text(fd,'member_id'),attendance_date:text(fd,'attendance_date'),status,check_in_at:status==='present'?new Date().toISOString():null,note:optional(fd,'note'),marked_by:user.id};const {error}=await supabase.from('attendance').upsert(record,{onConflict:'member_id,attendance_date'});if(error)throw new Error(error.message);revalidatePath('/admin/attendance');revalidatePath('/admin/attendance-history')}
export async function deleteAttendance(fd:FormData){const {supabase}=await requireAdmin();const {error}=await supabase.from('attendance').delete().eq('id',text(fd,'id'));if(error)throw new Error(error.message);revalidatePath('/admin/attendance-history')}
export async function updateLeave(fd:FormData){const {supabase}=await requireAdmin();const {error}=await supabase.from('leave_requests').update({status:text(fd,'status')}).eq('id',text(fd,'id'));if(error)throw new Error(error.message);revalidatePath('/admin/attendance-history')}

export async function saveTrainer(fd:FormData){const {supabase}=await requireAdmin();const id=text(fd,'id'),name=text(fd,'name');const uploaded=await uploadImage(fd,'image','trainers');const record={name,slug:text(fd,'slug')||slugify(name),specialty:optional(fd,'specialty'),bio:optional(fd,'bio'),image_url:uploaded||optional(fd,'current_image'),certifications:text(fd,'certifications').split(',').map(x=>x.trim()).filter(Boolean),experience_years:Number(text(fd,'experience_years')||0),sort_order:Number(text(fd,'sort_order')||0),instagram:optional(fd,'instagram'),facebook:optional(fd,'facebook'),youtube:optional(fd,'youtube'),tiktok:optional(fd,'tiktok'),is_featured:checked(fd,'is_featured'),is_visible:checked(fd,'is_visible')};const result=id?await supabase.from('trainers').update(record).eq('id',id):await supabase.from('trainers').insert(record);if(result.error)throw new Error(result.error.message);redirect('/admin/trainers?saved=1')}
export async function deleteTrainer(fd:FormData){const {supabase}=await requireAdmin();const {error}=await supabase.from('trainers').delete().eq('id',text(fd,'id'));if(error)throw new Error(error.message);revalidatePath('/admin/trainers')}

export async function saveGalleryItem(fd:FormData){const {supabase}=await requireAdmin();const uploaded=await uploadImage(fd,'image','gallery');if(!uploaded)throw new Error('Choose an image.');const {error}=await supabase.from('gallery_items').insert({image_url:uploaded,category:text(fd,'category')||'Gym Floor',caption:optional(fd,'caption'),sort_order:Number(text(fd,'sort_order')||0),is_active:checked(fd,'is_active')});if(error)throw new Error(error.message);redirect('/admin/gallery?uploaded=1')}
export async function updateGalleryItem(fd:FormData){const {supabase}=await requireAdmin();const {error}=await supabase.from('gallery_items').update({category:text(fd,'category'),caption:optional(fd,'caption'),sort_order:Number(text(fd,'sort_order')||0),is_active:checked(fd,'is_active')}).eq('id',text(fd,'id'));if(error)throw new Error(error.message);revalidatePath('/admin/gallery')}
export async function deleteGalleryItem(fd:FormData){const {supabase}=await requireAdmin();const {error}=await supabase.from('gallery_items').delete().eq('id',text(fd,'id'));if(error)throw new Error(error.message);revalidatePath('/admin/gallery')}

export async function updatePayment(fd:FormData){const {supabase,user}=await requireAdmin();const status=text(fd,'status');const {error}=await supabase.from('payment_requests').update({status,reviewed_at:new Date().toISOString(),reviewed_by:user.id}).eq('id',text(fd,'id'));if(error)throw new Error(error.message);revalidatePath('/admin/payments')}

export async function saveSettings(fd:FormData){const {supabase}=await requireAdmin();const keys=['gym_name','email','phone','whatsapp','address','city','weekday_hours','weekend_hours','facebook','instagram','tiktok','youtube','hero_kicker','hero_title','hero_copy','active_members_label','trainers_label','years_label','story_title','story_body','mission','vision','values_copy','founder_name','founder_note','certifications','footer_copy'];const record:Record<string,string|null>={};for(const key of keys)record[key]=optional(fd,key);for(const required of ['gym_name','email','phone','whatsapp','address','city','weekday_hours','weekend_hours','hero_kicker','hero_title','hero_copy','active_members_label','trainers_label','years_label','story_title','story_body','mission','vision','values_copy','founder_name','founder_note','certifications','footer_copy'])record[required]=text(fd,required);const {error}=await supabase.from('site_settings').update(record).eq('id',true);if(error)throw new Error(error.message);revalidatePath('/', 'layout');redirect('/admin/settings?saved=1')}
