import Link from 'next/link'
import {Pencil,Plus,Trash2} from 'lucide-react'
import {AdminPageHeading,SubmitButton} from '@/components/admin-ui'
import {EmptyState,Notice,StatusPill} from '@/components/ui'
import {formatPKR} from '@/lib/data'
import {requireAdmin} from '@/lib/site'
import {deletePlan} from '../actions'
export const metadata={title:'Membership Plans | Fitness Pro Admin'}
export default async function Plans({searchParams}:{searchParams:Promise<{saved?:string;created?:string}>}){const [{supabase},query]=await Promise.all([requireAdmin(),searchParams]);const {data:plans}=await supabase.from('membership_plans').select('*').order('sort_order');return <>{(query.saved||query.created)&&<Notice kind="success">Membership plan saved.</Notice>}<AdminPageHeading eyebrow="Website pricing" title="Membership plans" copy="Manage plan names, monthly pricing, features, visibility and display order." actions={<Link className="button" href="/admin/plans/new"><Plus/>Add plan</Link>}/>{plans?.length?<div className="dataCard"><div className="tableWrap"><table className="dataTable"><thead><tr><th>Order</th><th>Plan</th><th>Price</th><th>Period</th><th>Features</th><th>Popular</th><th>Status</th><th></th></tr></thead><tbody>{plans.map(p=><tr key={p.id}><td>{p.sort_order}</td><td><strong>{p.name}</strong><small>{p.tagline||'—'}</small></td><td>{formatPKR(p.price)}</td><td>{p.billing_period}</td><td>{p.features?.length||0}</td><td>{p.is_popular?'Yes':'No'}</td><td><StatusPill value={p.is_active?'active':'hidden'}/></td><td><div className="tableActions"><Link className="iconButton" href={`/admin/plans/${p.id}`} aria-label={`Edit ${p.name}`}><Pencil/></Link><form action={deletePlan}><input type="hidden" name="id" value={p.id}/><SubmitButton className="iconButton danger" confirm={`Delete ${p.name}? Existing members will keep their records without a linked plan.`}><Trash2/></SubmitButton></form></div></td></tr>)}</tbody></table></div></div>:<EmptyState title="No membership plans" copy="Create the first public plan card." href="/admin/plans/new" label="Add plan"/>}</>}
