import Link from 'next/link'
import {Check,Link2,Search,X} from 'lucide-react'
import {AdminPageHeading,SubmitButton} from '@/components/admin-ui'
import {EmptyState,StatusPill} from '@/components/ui'
import {requireAdmin} from '@/lib/site'
import {setMemberState} from '../actions'
export const metadata={title:'Registrations | Fitness Pro Admin'}
function planName(value:unknown){if(Array.isArray(value))return value[0]?.name||'—';if(value&&typeof value==='object'&&'name'in value)return String((value as {name:string}).name);return '—'}
export default async function Registrations({searchParams}:{searchParams:Promise<{q?:string;status?:string;link?:string}>}){const [{supabase},query]=await Promise.all([requireAdmin(),searchParams]);const q=(query.q||'').replace(/[(),]/g,''),status=query.status||'pending',link=query.link||'all';let request=supabase.from('members').select('*,membership_plans(name)').order('created_at',{ascending:false});if(q)request=request.or(`full_name.ilike.%${q}%,email.ilike.%${q}%,phone.ilike.%${q}%`);if(status!=='all')request=request.eq('approval_status',status);if(link==='linked')request=request.not('auth_user_id','is',null);if(link==='not-linked')request=request.is('auth_user_id',null);const {data:members}=await request;return <><AdminPageHeading eyebrow="Account approvals" title="Registrations" copy="Review online sign-ups and manually created members before enabling attendance access."/><form className="adminFilterBar"><label className="searchBox"><Search/><input name="q" defaultValue={query.q||''} placeholder="Search registrations"/></label><select name="status" defaultValue={status}><option value="all">All statuses</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select><select name="link" defaultValue={link}><option value="all">All account states</option><option value="linked">Linked online account</option><option value="not-linked">Not linked</option></select><button className="button buttonSmall">Filter</button></form>{members?.length?<div className="registrationGrid">{members.map(m=><article className="adminCard" key={m.id}><div className="messageHead"><div className="avatar">{m.full_name.slice(0,1)}</div><div><h2>{m.full_name}</h2><p>{m.email||m.phone}</p></div><StatusPill value={m.approval_status}/></div><dl><div><dt>Plan</dt><dd>{planName(m.membership_plans)}</dd></div><div><dt>Account</dt><dd>{m.auth_user_id?<><Link2/>Linked</>:'Manual record'}</dd></div><div><dt>Registered</dt><dd>{new Date(m.created_at).toLocaleString('en-PK')}</dd></div></dl><div className="buttonRow">{m.approval_status!=='approved'&&<form action={setMemberState}><input type="hidden" name="id" value={m.id}/><input type="hidden" name="approval_status" value="approved"/><SubmitButton><Check/>Approve</SubmitButton></form>}{m.approval_status!=='rejected'&&<form action={setMemberState}><input type="hidden" name="id" value={m.id}/><input type="hidden" name="approval_status" value="rejected"/><SubmitButton className="button buttonGhost"><X/>Reject</SubmitButton></form>}<Link className="textLink" href={`/admin/members/${m.id}`}>Open member</Link></div></article>)}</div>:<EmptyState title="No registrations match" copy="Try a different approval or account filter."/>}</>}
