import Link from 'next/link'
import {Mail,Phone,Trash2} from 'lucide-react'
import {AdminPageHeading,SubmitButton} from '@/components/admin-ui'
import {EmptyState,StatusPill} from '@/components/ui'
import {requireAdmin} from '@/lib/site'
import {deleteMessage,updateMessage} from '../actions'
export const metadata={title:'Messages | Fitness Pro Admin'}
const statuses=['all','new','contacted','resolved','cancelled','archived']
export default async function Messages({searchParams}:{searchParams:Promise<{status?:string}>}){const [{supabase},query]=await Promise.all([requireAdmin(),searchParams]);const status=statuses.includes(query.status||'')?query.status!:'all';let request=supabase.from('contact_messages').select('*').order('created_at',{ascending:false});if(status!=='all')request=request.eq('status',status);const {data:messages}=await request;return <><AdminPageHeading eyebrow="Inbox" title="Messages" copy="Review website enquiries and move each conversation through a clear status."/><div className="adminFilters"><div className="filterTabs">{statuses.map(s=><Link className={status===s?'active':''} href={`/admin/messages?status=${s}`} key={s}>{s[0].toUpperCase()+s.slice(1)}</Link>)}</div></div>{messages?.length?<div className="messageStack">{messages.map(message=><article className="adminCard messageCard" key={message.id}><div className="messageHead"><div className="avatar">{message.name.slice(0,1).toUpperCase()}</div><div><h2>{message.name}</h2><p>{message.subject||'General enquiry'} • {new Date(message.created_at).toLocaleString('en-PK')}</p></div><StatusPill value={message.status}/></div><p className="messageBody">{message.message}</p><div className="messageContacts"><a href={`mailto:${message.email}`}><Mail/>{message.email}</a>{message.phone&&<a href={`tel:${message.phone}`}><Phone/>{message.phone}</a>}</div><form action={updateMessage} className="messageEditor"><input type="hidden" name="id" value={message.id}/><label>Status<select name="status" defaultValue={message.status}>{statuses.slice(1).map(s=><option key={s}>{s}</option>)}</select></label><label>Internal note<textarea name="admin_note" rows={2} defaultValue={message.admin_note||''} placeholder="Private follow-up note"/></label><SubmitButton>Save update</SubmitButton></form><form action={deleteMessage} className="cornerAction"><input type="hidden" name="id" value={message.id}/><SubmitButton className="iconButton danger" confirm="Delete this message permanently?"><Trash2/></SubmitButton></form></article>)}</div>:<EmptyState title="No messages in this view" copy="New contact form submissions will appear here."/>}</>}
