
@import url('https://fonts.googleapis.com/css2?family=Anton&family=Inter:wght@400;500;600;700;800;900&display=swap');
:root{--bg:#08090a;--panel:#111315;--panel2:#17191b;--yellow:#f6c800;--yellow2:#ffdb35;--muted:#a5a8ad;--white:#f7f7f5;--line:#292c30}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--white);font-family:Inter,system-ui,sans-serif}a{text-decoration:none;color:inherit}button,input,select,textarea{font:inherit}
.container{width:min(1180px,92%);margin:auto}.section{padding:88px 0}.eyebrow{color:var(--yellow);font-weight:900;letter-spacing:.12em;text-transform:uppercase;font-size:13px}.title{font-family:Anton,sans-serif;font-size:clamp(42px,6vw,72px);line-height:.98;text-transform:uppercase;margin:10px 0 18px}.subtitle{color:var(--muted);max-width:650px;line-height:1.7}.btn{display:inline-flex;align-items:center;justify-content:center;gap:8px;padding:13px 20px;border-radius:8px;border:1px solid var(--yellow);background:var(--yellow);color:#08090a;font-weight:900;cursor:pointer}.btn.alt{background:transparent;color:var(--white)}.btn.danger{background:#e5484d;border-color:#e5484d;color:white}.grid{display:grid;gap:18px}.cards3{grid-template-columns:repeat(3,1fr)}.cards4{grid-template-columns:repeat(4,1fr)}.card{background:linear-gradient(180deg,#17191b,#0f1112);border:1px solid var(--line);border-radius:16px;overflow:hidden}.pad{padding:22px}.price{font-family:Anton;font-size:42px;color:var(--yellow)}.small{font-size:13px;color:var(--muted)}
.nav{position:fixed;top:0;left:0;right:0;z-index:50;background:rgba(8,9,10,.82);backdrop-filter:blur(14px);border-bottom:1px solid rgba(255,255,255,.07)}.navin{height:70px;display:flex;align-items:center;justify-content:space-between}.brand{display:flex;align-items:center;gap:10px;font-weight:900}.brandmark{width:42px;height:42px;border:2px solid var(--yellow);border-radius:12px;display:grid;place-items:center;color:var(--yellow);font-family:Anton;font-size:22px}.links{display:flex;gap:24px;color:#d7d7d7;font-size:14px;font-weight:700}.links a:hover{color:var(--yellow)}.mobile{display:none}
.hero{min-height:760px;padding-top:70px;display:grid;align-items:center;background:linear-gradient(90deg,rgba(5,6,7,.97) 0%,rgba(5,6,7,.78) 42%,rgba(5,6,7,.18) 100%),url('https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1800&q=85') center/cover}.hero h1{font-family:Anton;font-size:clamp(64px,10vw,128px);line-height:.88;margin:18px 0;text-transform:uppercase}.hero h1 span{color:var(--yellow)}.hero p{max-width:590px;color:#d1d1d1;line-height:1.8}.heroBtns{display:flex;gap:12px;flex-wrap:wrap;margin-top:26px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;margin-top:55px;background:var(--line)}.stat{background:#0c0e0f;padding:20px}.stat b{display:block;font-family:Anton;font-size:28px;color:var(--yellow)}
.sectionHead{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:30px}.goal img,.trainer img,.gallery img{width:100%;height:220px;object-fit:cover}.goal h3,.trainer h3{margin:12px 0 4px}.goal p,.trainer p{color:var(--muted);font-size:13px;line-height:1.6}.package{position:relative}.package.bronze{border-color:#a66b3f}.package.silver{border-color:#9aa0aa}.package.gold{border-color:var(--yellow)}.packageHead{padding:15px 20px;font-weight:900;text-transform:uppercase;background:linear-gradient(90deg,#2a2d30,#151719)}.gold .packageHead{background:var(--yellow);color:#0a0a0a}.features{list-style:none;padding:0;margin:20px 0;display:grid;gap:10px;color:#ddd;font-size:14px}.features li:before{content:'✓';color:var(--yellow);font-weight:900;margin-right:8px}
.passes{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}.pass{padding:25px;border:1px solid var(--line);border-radius:16px;background:var(--panel)}.duration{display:grid;grid-template-columns:1.1fr repeat(3,1fr);border:1px solid var(--line);border-radius:16px;overflow:hidden}.duration>div{padding:17px;border-right:1px solid var(--line);border-bottom:1px solid var(--line)}.duration .head{background:var(--yellow);color:#090909;font-weight:900}.duration .label{color:var(--yellow);font-weight:900}
.contact{display:grid;grid-template-columns:1fr 1fr;gap:30px}.contactBox{padding:30px;border:1px solid var(--line);border-radius:18px;background:var(--panel)}.contactRow{display:flex;gap:14px;align-items:center;margin:18px 0}.icon{width:42px;height:42px;border-radius:10px;background:#202307;color:var(--yellow);display:grid;place-items:center}.map{min-height:330px;border-radius:18px;background:linear-gradient(135deg,#171b13,#0f1112);border:1px solid var(--line);display:grid;place-items:center;text-align:center}
footer{padding:45px 0;border-top:1px solid var(--line);color:#888}.footergrid{display:grid;grid-template-columns:2fr 1fr 1fr;gap:30px}.admin{min-height:100vh;background:#090a0b}.adminLayout{display:grid;grid-template-columns:250px 1fr}.sidebar{position:fixed;top:0;bottom:0;width:250px;background:#0e1011;border-right:1px solid var(--line);padding:24px}.adminMain{margin-left:250px;padding:30px}.sideLinks{display:grid;gap:7px;margin-top:30px}.sideLinks a{padding:12px;border-radius:8px;color:#aaa}.sideLinks a.active,.sideLinks a:hover{background:#1a1c1e;color:var(--yellow)}.metric{padding:20px;background:#121416;border:1px solid var(--line);border-radius:12px}.metric b{font-family:Anton;font-size:34px;color:var(--yellow)}.table{width:100%;border-collapse:collapse}.table th,.table td{padding:14px;border-bottom:1px solid var(--line);text-align:left;font-size:13px}.input{width:100%;background:#0c0e0f;color:#fff;border:1px solid var(--line);padding:12px;border-radius:8px;outline:none}.input:focus{border-color:var(--yellow)}.formgrid{display:grid;gap:14px}.toast{padding:12px;border-radius:8px;background:#17220f;border:1px solid #40551a;color:#cde987}
@media(max-width:900px){.links{display:none}.mobile{display:block}.cards4{grid-template-columns:repeat(2,1fr)}.cards3{grid-template-columns:1fr}.hero{min-height:720px}.stats{grid-template-columns:repeat(2,1fr)}.contact{grid-template-columns:1fr}.footergrid{grid-template-columns:1fr}.duration{grid-template-columns:1fr 1fr}.duration .head:first-child{display:none}.adminLayout{display:block}.sidebar{position:static;width:auto}.adminMain{margin-left:0}.sideLinks{grid-template-columns:repeat(2,1fr)}}
@media(max-width:560px){.cards4{grid-template-columns:1fr}.passes{grid-template-columns:1fr}.hero h1{font-size:68px}.section{padding:65px 0}.stats{grid-template-columns:1fr 1fr}.duration{font-size:12px}.brand span{display:none}}
