'use client'
import Image from 'next/image'
import {Phone,MapPin,Mail,Clock,ArrowRight} from 'lucide-react'
import {plans,diet,passes,durations,goals,trainers,gallery} from '@/lib/data'
import {createClient} from '@/lib/supabase-browser'
import {Fragment,useState} from 'react'

export default function Home(){
 const [selected,setSelected]=useState(''); const [form,setForm]=useState({name:'',phone:'',email:'',plan:''}); const [sent,setSent]=useState(false); const [sending,setSending]=useState(false); const [submitError,setSubmitError]=useState('')
 async function submit(e:React.FormEvent){e.preventDefault();setSending(true);setSent(false);setSubmitError('');const supabase=createClient();const {error}=await supabase.from('membership_requests').insert({...form,plan:selected||form.plan});if(error){setSubmitError('We could not send your request right now. Please contact us by phone or WhatsApp.')}else{setSent(true);setSelected('');setForm({name:'',phone:'',email:'',plan:''})}setSending(false)}
 return <main>
 <nav className="nav"><div className="container navin"><a className="brand" href="#"><span className="brandmark">FP</span><span>FITNESS <b style={{color:'var(--yellow)'}}>PRO</b></span></a><div className="links"><a href="#about">About</a><a href="#plans">Plans</a><a href="#trainers">Trainers</a><a href="#gallery">Gallery</a><a href="#contact">Contact</a></div><a className="btn" href="#join">Join Now</a></div></nav>
 <section className="hero"><div className="container"><div className="eyebrow">Gym & Fitness Center • Abbottabad</div><h1>Build a<br/><span>Stronger</span><br/>You</h1><p>Train with purpose. Transform your body. Build the discipline that carries into every part of life. Fitness Pro gives you modern equipment, expert coaching and plans built for your goals.</p><div className="heroBtns"><a className="btn" href="#join">Join Now <ArrowRight size={17}/></a><a className="btn alt" href="#plans">View Plans</a></div><div className="stats"><div className="stat"><b>500+</b>Active Members</div><div className="stat"><b>10+</b>Expert Trainers</div><div className="stat"><b>24/7</b>Modern Equipment</div><div className="stat"><b>100%</b>Results Focused</div></div></div></section>
 <section id="about" className="section"><div className="container"><div className="sectionHead"><div><div className="eyebrow">Train with purpose</div><h2 className="title">Your Fitness Goals</h2><p className="subtitle">Whatever your goal, we have the right plan and support for you.</p></div></div><div className="grid cards4">{goals.map(g=><div className="card goal" key={g[0]}><Image src={g[1]} alt={g[0]} width={600} height={400}/><div className="pad"><h3>{g[0]}</h3><p>{g[2]}</p></div></div>)}</div></div></section>
 <section id="plans" className="section" style={{background:'#0b0d0e'}}><div className="container"><div className="eyebrow">Membership</div><h2 className="title">Packages</h2><p className="subtitle">Choose the package that fits your fitness journey.</p><div className="grid cards3" style={{marginTop:30}}>{plans.map(p=><div className={'card package '+p.tone} key={p.name}><div className="packageHead">{p.name}</div><div className="pad"><div className="price">Rs. {p.price.toLocaleString()}</div><ul className="features">{p.features.map(f=><li key={f}>{f}</li>)}</ul><button className="btn" onClick={()=>{setSelected(p.name);document.getElementById('join')?.scrollIntoView()}}>Get Started</button></div></div>)}</div>
 <div style={{marginTop:60}}><div className="eyebrow">Diet Plan</div><h2 className="title" style={{fontSize:48}}>Nutrition</h2><div className="passes">{diet.map(d=><div className="pass" key={d.name}><h3>{d.name}</h3><div className="price">Rs. {d.price.toLocaleString()}</div><p className="small">Personalized support for your nutrition goals.</p></div>)}</div></div>
 <div style={{marginTop:60}}><div className="eyebrow">Flexible passes</div><h2 className="title" style={{fontSize:48}}>Daily / Weekly</h2><div className="passes">{passes.map(p=><div className="pass" key={p.period}><h3>{p.period}</h3>{p.items.map(i=><div style={{display:'flex',justifyContent:'space-between',padding:'10px 0',borderBottom:'1px solid var(--line)'}} key={i[0]}><span>{i[0]}</span><b style={{color:'var(--yellow)'}}>Rs. {i[1]}</b></div>)}</div>)}</div></div>
 <div style={{marginTop:60}}><div className="eyebrow">50% OFF IN ADMISSION</div><h2 className="title" style={{fontSize:48}}>Long-Term Plans</h2><div className="duration"><div className="head">Duration</div><div className="head">Bronze</div><div className="head">Silver</div><div className="head">Gold</div>{durations.map(r=><Fragment key={String(r[0])}><div className="label">{r[0]}</div><div>Rs. {r[1].toLocaleString()}</div><div>Rs. {r[2].toLocaleString()}</div><div style={{color:'var(--yellow)',fontWeight:900}}>Rs. {r[3].toLocaleString()}</div></Fragment>)}</div></div></div></section>
 <section id="trainers" className="section"><div className="container"><div className="eyebrow">Professional coaching</div><h2 className="title">Our Trainers</h2><p className="subtitle">Trainer profiles will appear here when added from the admin portal.</p>{trainers.length ? <div className="grid cards4" style={{marginTop:30}}>{trainers.map(t=><div className="card trainer" key={t[0]}><Image src={t[2]} alt={t[0]} width={600} height={500}/><div className="pad"><h3>{t[0]}</h3><p>{t[1]}</p></div></div>)}</div> : <div className="card pad" style={{marginTop:30}}><h3>Trainer profiles coming soon</h3><p className="small">The gym can add trainer names, specialties and photos after the admin portal is connected.</p></div>}</div></section>
 <section id="gallery" className="section" style={{background:'#0b0d0e'}}><div className="container"><div className="eyebrow">Inside Fitness Pro</div><h2 className="title">Gym Gallery</h2><div className="grid cards3" style={{marginTop:30}}>{gallery.map((g,i)=><div className="card gallery" key={g}><Image src={g} alt={'Fitness Pro gym photo '+(i+1)} width={800} height={500}/></div>)}</div></div></section>
 <section id="join" className="section"><div className="container contact"><div><div className="eyebrow">Start today</div><h2 className="title">Join Fitness Pro</h2><p className="subtitle">Send your details and our team will contact you on WhatsApp or phone.</p><div className="contactBox" style={{marginTop:25}}><form onSubmit={submit} className="formgrid"><input className="input" required maxLength={120} placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className="input" required maxLength={40} placeholder="Phone / WhatsApp" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input className="input" type="email" maxLength={254} placeholder="Email (optional)" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><select className="input" value={selected||form.plan} onChange={e=>{setSelected(e.target.value);setForm({...form,plan:e.target.value})}}><option value="">Select a package</option>{plans.map(p=><option key={p.name}>{p.name}</option>)}{diet.map(d=><option key={d.name}>{d.name}</option>)}</select><button className="btn" type="submit" disabled={sending}>{sending?'Sending…':'Submit Membership Request'}</button><div aria-live="polite">{sent&&<div className="toast">Request received. We will contact you shortly.</div>}{submitError&&<div style={{color:'#ff8a8a',marginTop:10}}>{submitError}</div>}</div></form></div></div><div id="contact"><div className="eyebrow">Visit us</div><h2 className="title" style={{fontSize:48}}>Contact</h2><div className="contactBox"><div className="contactRow"><div className="icon"><Phone size={19}/></div><div><b>Phone / WhatsApp</b><br/><a href="https://wa.me/923485581969" target="_blank">0348 5581969</a></div></div><div className="contactRow"><div className="icon"><Mail size={19}/></div><div><b>Email</b><br/>min955378@gmail.com</div></div><div className="contactRow"><div className="icon"><MapPin size={19}/></div><div><b>Location</b><br/>5752+WRX, Orish Colony Rd, Nawan Shehr Town, Abbottabad, Pakistan</div></div><div className="contactRow"><div className="icon"><Clock size={19}/></div><div><b>Opening Hours</b><br/>Mon - Fri • 6:00 AM - 10:00 AM & 3:00 PM - 11:30 PM<br/>Sat - Sun • Closed</div></div></div><div className="map" style={{marginTop:18}}><MapPin size={40} color="var(--yellow)"/><div><b>Fitness Pro • Abbottabad</b><br/><span className="small">5752+WRX, Orish Colony Rd, Nawan Shehr Town, Abbottabad, Pakistan</span></div></div></div></div></section>
 <footer><div className="container footergrid"><div><div className="brand"><span className="brandmark">FP</span><span>FITNESS <b style={{color:'var(--yellow)'}}>PRO</b></span></div><p>Train. Transform. Achieve.</p></div><div><b>Quick Links</b><p><a href="#plans">Plans</a></p><p><a href="#trainers">Trainers</a></p><p><a href="#gallery">Gallery</a></p></div><div><b>Contact</b><p>0348 5581969</p><p>Abbottabad</p></div></div></footer>
 </main>
}
