import Image from 'next/image'
import Link from 'next/link'
import {ArrowRight,CalendarDays,Check,Clock3,Dumbbell,HeartPulse,ShieldCheck,Sparkles,UsersRound} from 'lucide-react'
import {formatPKR,trainingGoals} from '@/lib/data'
import {getPublicData} from '@/lib/site'
import {SiteShell} from '@/components/site-shell'
import {EmptyState,SectionHeading} from '@/components/ui'

export default async function Home(){
 const {settings,plans,dietPlans,rates,durations,trainers,gallery}=await getPublicData()
 return <SiteShell settings={settings}><main>
  <section className="homeHero"><Image src="/images/fitness-pro-hero.jpg" alt="Modern Fitness Pro strength training floor" fill priority sizes="100vw"/><div className="heroShade"/><div className="container heroContent"><span className="eyebrow">{settings.hero_kicker}</span><h1>{settings.hero_title}</h1><p>{settings.hero_copy}</p><div className="buttonRow"><Link className="button" href="/register">Start your membership <ArrowRight size={18}/></Link><Link className="button buttonGhost" href="#plans">See plans</Link></div></div><div className="container heroStats"><div><strong>{settings.active_members_label}</strong><span>Members supported</span></div><div><strong>{settings.trainers_label}</strong><span>Coaching expertise</span></div><div><strong>{settings.years_label}</strong><span>Years of progress</span></div></div></section>

  <section className="section"><div className="container"><SectionHeading eyebrow="Why Fitness Pro" title="Everything you need to keep moving" copy="A serious training environment without the intimidation—built around consistent progress."/><div className="featureGrid"><article><Dumbbell/><h3>Purpose-built equipment</h3><p>Strength, functional and conditioning zones organized for productive sessions.</p></article><article><UsersRound/><h3>Coaching that listens</h3><p>Practical guidance shaped around your experience, schedule and goals.</p></article><article><ShieldCheck/><h3>Respectful community</h3><p>A clean, welcoming space where beginners and experienced lifters can focus.</p></article><article><Clock3/><h3>Extended weekday hours</h3><p>Morning and evening sessions that fit around work, study and family.</p></article></div></div></section>

  <section className="section sectionTint"><div className="container"><SectionHeading eyebrow="Train your way" title="Goals become a plan" copy="Start where you are. We will help you build the next step."/><div className="goalGrid">{trainingGoals.map(goal=><article className="imageCard" key={goal.title}><Image src={goal.image} alt={goal.title} fill sizes="(max-width: 800px) 100vw, 33vw"/><div className="imageCardShade"/><div><h3>{goal.title}</h3><p>{goal.copy}</p></div></article>)}</div></div></section>

  <section className="section" id="plans"><div className="container"><SectionHeading eyebrow="Memberships" title="Choose your starting point" copy="Straightforward monthly options with room to upgrade as your goals grow."/><div className="planGrid">{plans.map(plan=><article className={`planCard ${plan.is_popular?'isPopular':''}`} key={plan.id}>{plan.is_popular&&<span className="popularTag"><Sparkles size={14}/>Most popular</span>}<p className="planTagline">{plan.tagline}</p><h3>{plan.name}</h3><div className="planPrice">{formatPKR(plan.price)}<small> / {plan.billing_period.toLowerCase()}</small></div><ul>{plan.features.map(feature=><li key={feature}><Check size={16}/>{feature}</li>)}</ul><Link className={plan.is_popular?'button':'button buttonGhost'} href={`/register?plan=${encodeURIComponent(plan.id)}`}>Choose {plan.name}</Link></article>)}</div>
  <div className="pricingSplit"><div><SectionHeading eyebrow="Nutrition" title="Diet support" copy="Simple guidance for meals that support your training."/><div className="compactCards">{dietPlans.map(plan=><article key={plan.id}><HeartPulse/><div><h3>{plan.name}</h3><p>{plan.blurb}</p></div><strong>{formatPKR(plan.price)}</strong><Link aria-label={`Choose ${plan.name} diet plan`} href={`/payment?kind=diet&plan=${encodeURIComponent(plan.name)}`}><ArrowRight/></Link></article>)}</div></div><div><SectionHeading eyebrow="Flexible visits" title="Daily & weekly" copy="Train without a monthly commitment."/><div className="rateList">{rates.map(rate=><div key={rate.key}><span>{rate.label}</span><strong>{formatPKR(rate.amount)}</strong></div>)}</div></div></div>
  <div className="durationBlock"><SectionHeading eyebrow="Commit to progress" title="Long-term memberships" copy="Multi-month pricing across Bronze, Silver and Gold."/><div className="responsiveTable"><table><thead><tr><th>Duration</th><th>Bronze</th><th>Silver</th><th>Gold</th><th></th></tr></thead><tbody>{durations.map(row=><tr key={row.id}><td><CalendarDays size={16}/>{row.label}</td><td>{formatPKR(row.bronze_price)}</td><td>{formatPKR(row.silver_price)}</td><td>{formatPKR(row.gold_price)}</td><td><Link href={`/payment?kind=duration&plan=${encodeURIComponent(row.label)}`} aria-label={`Choose ${row.label}`}><ArrowRight size={17}/></Link></td></tr>)}</tbody></table></div></div></div></section>

  <section className="section sectionTint"><div className="container"><SectionHeading eyebrow="Coaching" title="Meet the team" copy="Qualified support for stronger, safer training." action={<Link className="textLink" href="/trainers">All trainers <ArrowRight size={16}/></Link>}/>{trainers.length?<div className="trainerGrid">{trainers.slice(0,3).map(t=><article className="trainerCard" key={t.id}>{t.image_url?<Image src={t.image_url} alt={t.name} width={600} height={720}/>:<div className="trainerPlaceholder"><Dumbbell/></div>}<div><span>{t.specialty||'Fitness coach'}</span><h3>{t.name}</h3><p>{t.experience_years?`${t.experience_years} years of experience`:t.bio}</p></div></article>)}</div>:<EmptyState title="Coach profiles are being prepared" copy="The Fitness Pro team is preparing trainer specialties, experience and certification details." href="/contact" label="Ask about coaching"/>}</div></section>

  <section className="section"><div className="container"><SectionHeading eyebrow="Inside Fitness Pro" title="The space to do the work" action={<Link className="textLink" href="/gallery">View gallery <ArrowRight size={16}/></Link>}/><div className="galleryPreview">{gallery.slice(0,4).map((item,index)=><figure key={item.id} className={index===0?'wide':''}><Image src={item.image_url} alt={item.caption||`Fitness Pro ${item.category}`} fill sizes="(max-width: 800px) 100vw, 50vw"/><figcaption><span>{item.category}</span>{item.caption}</figcaption></figure>)}</div></div></section>

  <section className="ctaBand"><div className="container"><div><span className="eyebrow">Your next session starts here</span><h2>Ready to build momentum?</h2><p>Register online. Our team will review your membership and help you get started.</p></div><div className="buttonRow"><Link className="button" href="/register">Join Fitness Pro <ArrowRight size={18}/></Link><Link className="button buttonGhost" href={`https://wa.me/${settings.whatsapp}`} target="_blank">WhatsApp us</Link></div></div></section>
 </main></SiteShell>
}
