'use client'
import Link from 'next/link'
import {Activity,CalendarCheck,CalendarClock,ChevronLeft,ClipboardList,CreditCard,ImageIcon,LayoutDashboard,Menu,MessageSquare,PanelLeftClose,PanelLeftOpen,Settings,Tags,UsersRound,UserSquare2,X} from 'lucide-react'
import {usePathname} from 'next/navigation'
import {useState} from 'react'
import {Logo} from './logo'
import {SignOutButton} from './sign-out-button'
const sections=[{label:'Overview',links:[['/admin/dashboard','Dashboard',LayoutDashboard]]},{label:'People',links:[['/admin/messages','Messages',MessageSquare],['/admin/members','Members',UsersRound],['/admin/registrations','Registrations',ClipboardList]]},{label:'Operations',links:[['/admin/attendance','Attendance',CalendarCheck],['/admin/attendance-history','History',CalendarClock],['/admin/payments','Payments',CreditCard]]},{label:'Website',links:[['/admin/plans','Plans',Tags],['/admin/pricing','Pricing',Tags],['/admin/trainers','Trainers',UserSquare2],['/admin/gallery','Gallery',ImageIcon]]},{label:'System',links:[['/admin/activity','Activity',Activity],['/admin/settings','Settings',Settings]]}] as const
export function AdminShell({email,children}:{email:string;children:React.ReactNode}){const path=usePathname();const [collapsed,setCollapsed]=useState(false),[mobile,setMobile]=useState(false);return <div className={`adminApp ${collapsed?'isCollapsed':''}`}><aside className={mobile?'mobileOpen':''}><div className="adminBrand"><Logo compact={collapsed}/><button className="iconButton desktopCollapse" onClick={()=>setCollapsed(!collapsed)} aria-label={collapsed?'Expand sidebar':'Collapse sidebar'}>{collapsed?<PanelLeftOpen/>:<PanelLeftClose/>}</button><button className="iconButton mobileClose" onClick={()=>setMobile(false)} aria-label="Close sidebar"><X/></button></div><nav>{sections.map(section=><div key={section.label}><span>{section.label}</span>{section.links.map(([href,label,Icon])=><Link onClick={()=>setMobile(false)} className={path===href||path.startsWith(href+'/')?'active':''} href={href} key={href} title={collapsed?label:undefined}><Icon/>{!collapsed&&label}</Link>)}</div>)}</nav><div className="adminSidebarFooter"><Link href="/"><ChevronLeft/> {!collapsed&&'View website'}</Link>{!collapsed&&<small>{email}</small>}</div></aside>{mobile&&<button className="adminScrim" onClick={()=>setMobile(false)} aria-label="Close menu"/>}<div className="adminWorkspace"><header><button className="iconButton adminMobileMenu" onClick={()=>setMobile(true)} aria-label="Open sidebar"><Menu/></button><div><strong>Fitness Pro</strong><span>Management portal</span></div><SignOutButton/></header><main>{children}</main></div></div>}
