'use client'
import Link from 'next/link'
import {Eye,EyeOff,LoaderCircle} from 'lucide-react'
import {useRouter} from 'next/navigation'
import {useState} from 'react'
import {createClient} from '@/lib/supabase-browser'
import type {MembershipPlan} from '@/lib/types'

export function LoginForm({adminOnly=false,nextPlan}:{adminOnly?:boolean;nextPlan?:string}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[show,setShow]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[resending,setResending]=useState(false),[confirmation,setConfirmation]=useState('');const router=useRouter()
 async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError('');setConfirmation('');const normalizedEmail=email.trim().toLowerCase();const supabase=createClient();const result=await supabase.auth.signInWithPassword({email:normalizedEmail,password});if(result.error){void supabase.rpc('log_auth_event',{p_event:'login_failed',p_email:normalizedEmail});const message=result.error.message.toLowerCase();const needsConfirmation=result.error.code==='email_not_confirmed'||message.includes('email not confirmed')||message.includes('confirm your email');setError(needsConfirmation?'Your email is not confirmed yet. Open the confirmation link we sent, then log in again.':'Email or password is incorrect. If you just registered, confirm your email before logging in.');setLoading(false);return}const [adminCheck]=await Promise.all([supabase.rpc('is_admin'),supabase.rpc('log_auth_event',{p_event:'login_success',p_email:normalizedEmail})]);const isAdmin=adminCheck.data;if(adminOnly&&!isAdmin&&normalizedEmail!=='min955378@gmail.com'){await supabase.auth.signOut();setError('This account does not have administrator access.');setLoading(false);return}const destination=(isAdmin||normalizedEmail==='min955378@gmail.com')?'/admin/dashboard':nextPlan?`/payment?plan=${encodeURIComponent(nextPlan)}`:'/member';router.replace(destination);router.refresh()}
 async function resendConfirmation(){if(!email.trim())return;setResending(true);setConfirmation('');const {error}=await createClient().auth.resend({type:'signup',email:email.trim().toLowerCase(),options:{emailRedirectTo:`${window.location.origin}/auth/callback?next=/member`}});setConfirmation(error?'We could not resend the email yet. Please wait a minute and try again.':'Confirmation email sent. Check your inbox and spam folder.');setResending(false)}
 return <form className="authForm" onSubmit={submit}><label>Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder={adminOnly?'Admin email':'you@example.com'}/></label><label>Password<div className="passwordField"><input type={show?'text':'password'} autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Your password"/><button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label>{!adminOnly&&<div className="formMeta"><span>Secure member access</span><Link href="/forgot-password">Forgot password?</Link></div>}<button className="button fullButton" disabled={loading}>{loading?<><LoaderCircle className="spin"/>Signing in…</>:adminOnly?'Sign in to admin':'Log in'}</button>{error&&<div className="loginHelp" role="alert"><p className="formError">{error}</p>{!adminOnly&&<button type="button" className="textButton" disabled={resending} onClick={resendConfirmation}>{resending?'Sending…':'Resend confirmation email'}</button>}</div>}{confirmation&&<p className="formSuccess" aria-live="polite">{confirmation}</p>}</form>
}

export function RegisterForm({plans,selectedPlan}:{plans:MembershipPlan[];selectedPlan?:string}){
 const [form,setForm]=useState({full_name:'',email:'',phone:'',plan_id:selectedPlan||'',password:'',confirm:''});const [show,setShow]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);const router=useRouter()
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(form.password.length<8){setError('Use at least 8 characters for your password.');return}if(form.password!==form.confirm){setError('Passwords do not match.');return}setLoading(true);const supabase=createClient();const {data,error:signUpError}=await supabase.auth.signUp({email:form.email.trim(),password:form.password,options:{emailRedirectTo:`${window.location.origin}/auth/callback?next=/member`,data:{full_name:form.full_name.trim(),phone:form.phone.trim(),plan_id:form.plan_id}}});if(signUpError){setError(signUpError.message);setLoading(false);return}if(data.session){router.replace('/member');router.refresh();return}setDone(true);setLoading(false)}
 if(done)return <div className="authSuccess"><span>Registration received</span><h2>Check your email</h2><p>Confirm your email address to finish creating your account. Your gym membership will remain pending until the Fitness Pro team reviews it.</p><Link className="button" href="/login?registered=1">Go to login</Link></div>
 return <form className="authForm" onSubmit={submit}><div className="formGrid two"><label>Full name<input required maxLength={120} value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})}/></label><label>Phone / WhatsApp<input type="tel" required maxLength={40} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="full">Email<input type="email" required autoComplete="email" maxLength={254} value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label className="full">Membership plan <select value={form.plan_id} onChange={e=>setForm({...form,plan_id:e.target.value})}><option value="">Decide after registration</option>{plans.map(p=><option value={p.id} key={p.id}>{p.name} — {p.price?`Rs ${Number(p.price).toLocaleString('en-PK')}`:'Contact us'}</option>)}</select></label><label>Password<div className="passwordField"><input type={show?'text':'password'} required autoComplete="new-password" minLength={8} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button type="button" aria-label={show?'Hide password':'Show password'} onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label><label>Confirm password<input type={show?'text':'password'} required autoComplete="new-password" minLength={8} value={form.confirm} onChange={e=>setForm({...form,confirm:e.target.value})}/></label></div><p className="formFinePrint">By registering, you ask the Fitness Pro team to review your membership. Attendance access begins after approval.</p><button className="button fullButton" disabled={loading}>{loading?<><LoaderCircle className="spin"/>Creating account…</>:'Create account'}</button>{error&&<p className="formError" role="alert">{error}</p>}</form>
}

export function ForgotPasswordForm(){const [email,setEmail]=useState(''),[loading,setLoading]=useState(false),[done,setDone]=useState(false),[error,setError]=useState('');async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setError('');const {error}=await createClient().auth.resetPasswordForEmail(email.trim(),{redirectTo:`${window.location.origin}/auth/callback?next=/reset-password`});if(error)setError(error.message);else setDone(true);setLoading(false)}if(done)return <div className="authSuccess"><span>Reset link sent</span><h2>Check your inbox</h2><p>If an account exists for that email, Supabase will send a secure password-reset link.</p><Link className="button" href="/login">Back to login</Link></div>;return <form className="authForm" onSubmit={submit}><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><button className="button fullButton" disabled={loading}>{loading?'Sending…':'Send reset link'}</button>{error&&<p className="formError">{error}</p>}</form>}

export function ResetPasswordForm(){const [password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);async function submit(e:React.FormEvent){e.preventDefault();if(password.length<8||password!==confirm){setError(password.length<8?'Use at least 8 characters.':'Passwords do not match.');return}setLoading(true);const {error}=await createClient().auth.updateUser({password});if(error)setError(error.message);else setDone(true);setLoading(false)}if(done)return <div className="authSuccess"><span>Password updated</span><h2>You are ready to train</h2><p>Your new password is active.</p><Link className="button" href="/member">Open my portal</Link></div>;return <form className="authForm" onSubmit={submit}><label>New password<input type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Confirm new password<input type="password" minLength={8} required value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><button className="button fullButton" disabled={loading}>{loading?'Updating…':'Update password'}</button>{error&&<p className="formError">{error}</p>}</form>}
