import Image from 'next/image'
import Link from 'next/link'
import {Dumbbell,Pencil,Plus,Trash2} from 'lucide-react'
import {AdminPageHeading,SubmitButton} from '@/components/admin-ui'
import {EmptyState,Notice,StatusPill} from '@/components/ui'
import {requireAdmin} from '@/lib/site'
import {deleteTrainer} from '../actions'
export const metadata={title:'Trainers | Fitness Pro Admin'}
export default async function TrainersAdmin({searchParams}:{searchParams:Promise<{saved?:string}>}){const [{supabase},query]=await Promise.all([requireAdmin(),searchParams]);const {data:trainers}=await supabase.from('trainers').select('*').order('sort_order');return <>{query.saved&&<Notice kind="success">Trainer saved.</Notice>}<AdminPageHeading eyebrow="Website content" title="Trainers" copy="Manage coaching profiles, credentials, social links, home-page placement and public visibility." actions={<Link className="button" href="/admin/trainers/new"><Plus/>Add trainer</Link>}/>{trainers?.length?<div className="trainerAdminGrid">{trainers.map(t=><article className="adminCard" key={t.id}><div className="trainerAdminImage">{t.image_url?<Image src={t.image_url} alt={t.name} fill sizes="280px"/>:<Dumbbell/>}</div><div><div className="rowBetween"><span className="eyebrow">Order {t.sort_order||0}</span><StatusPill value={t.is_visible?'active':'hidden'}/></div><h2>{t.name}</h2><p>{t.specialty||'No specialty added'}</p><small>{t.experience_years||0} years • {t.certifications?.length||0} certifications {t.is_featured?'• Featured':''}</small><div className="buttonRow"><Link className="button buttonSmall buttonGhost" href={`/admin/trainers/${t.id}`}><Pencil/>Edit</Link><form action={deleteTrainer}><input type="hidden" name="id" value={t.id}/><SubmitButton className="iconButton danger" confirm={`Delete ${t.name}?`}><Trash2/></SubmitButton></form></div></div></article>)}</div>:<EmptyState title="No trainers published" copy="Create the first coach profile for the public Trainers page." href="/admin/trainers/new" label="Add trainer"/>}</>}
