/* eslint-disable react-hooks/purity -- server reports intentionally use the current time */
import {Activity as ActivityIcon,LogIn,LogOut,Search,UserPlus,XCircle} from 'lucide-react'
import {AdminPageHeading} from '@/components/admin-ui'
import {EmptyState,StatusPill} from '@/components/ui'
import {requireAdmin} from '@/lib/site'
export const metadata={title:'Member Activity | Fitness Pro Admin'}
const eventTypes=['all','registered','login_success','login_failed','logout']
function memberName(value:unknown){const item=Array.isArray(value)?value[0]:value;return item&&typeof item==='object'&&'full_name'in item?String((item as {full_name:string}).full_name):null}
export default async function Activity({searchParams}:{searchParams:Promise<{event?:string;period?:string;q?:string}>}){const [{supabase},query]=await Promise.all([requireAdmin(),searchParams]);const event=eventTypes.includes(query.event||'')?query.event!:'all',period=['7','30','90','all'].includes(query.period||'')?query.period!:'30',q=(query.q||'').replace(/[(),]/g,'');let request=supabase.from('activity_events').select('*,members(full_name)').order('created_at',{ascending:false}).limit(500);if(event!=='all')request=request.eq('event_type',event);if(period!=='all')request=request.gte('created_at',new Date(Date.now()-Number(period)*86400000).toISOString());if(q)request=request.ilike('email',`%${q}%`);const {data:events}=await request;const icons={registered:UserPlus,login_success:LogIn,login_failed:XCircle,logout:LogOut} as const;return <><AdminPageHeading eyebrow="Security and engagement" title="Member activity" copy="Review registrations, successful sign-ins, failed attempts and logouts."/><form className="adminFilterBar"><label className="searchBox"><Search/><input name="q" defaultValue={query.q||''} placeholder="Search email"/></label><select name="event" defaultValue={event}><option value="all">All events</option><option value="registered">Registered</option><option value="login_success">Login success</option><option value="login_failed">Login failed</option><option value="logout">Logout</option></select><select name="period" defaultValue={period}><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="90">Last 90 days</option><option value="all">All activity</option></select><button className="button buttonSmall">Filter</button></form>{events?.length?<div className="activityTimeline">{events.map(event=>{const Icon=icons[event.event_type as keyof typeof icons]||ActivityIcon;return <article key={event.id}><span className={`activityIcon event-${event.event_type}`}><Icon/></span><div><strong>{memberName(event.members)||event.email||'Unknown account'}</strong><p>{String(event.event_type).replaceAll('_',' ')}</p></div><StatusPill value={event.event_type}/><time>{new Date(event.created_at).toLocaleString('en-PK')}</time></article>})}</div>:<EmptyState title="No activity matches" copy="Authentication events will appear here once members use their accounts."/>}</>}
